language: ruby
script: bundle exec rake test

rvm:
  - 1.9.3
  - 2.1.2

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.0-stable
  - gemfiles/Gemfile.rails-3.2-stable
  - gemfiles/Gemfile.rails-head

matrix:
  exclude:
    - rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.rails-head
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=1
